[package]
name = "lento"
readme = "README.md"
license = "MIT"
description = "Cross platform ui framework"

version = "0.1.0"
authors = ["KasonYang <me@kason.site>"]
edition = "2021"


[dependencies]
lento-macros = { path = "packages/lento-macros", version = "0.1.0" }

quick-js = {path = "third_party/quickjs-rs", package = "lento-quick-js", version = "0.4.2-alpha.0"}
yoga = { path = "third_party/yoga-rs", package = "lento-yoga", version = "0.4.0" }
winit = { path = "third_party/winit", package = "lento-winit", version = "0.30.5", features = ["android-native-activity"] }
skia-window = { path = "skia-window", version = "0.1.0" }

bitflags = "2.0"
lazy_static = "1.4"
skia-bindings = { path = "third_party/rust-skia/skia-bindings", package = "lento-skia-bindings", version = "0.75.0", default-features = false }


ureq = { version = "2.8.0", optional = true }
base64 = { version = "0.22.0" }
ordered-float = "3.9.2"
serde_json = "1.0.117"
serde = { version = "1.0.203", features = ["derive"] }
anyhow = { version = "1.0.75" }
reqwest = { version = "0.12.5",default-features = false, features = ["blocking", "native-tls-vendored", "multipart", "stream"] }
tokio = { version = "1.38.0", features = ["rt-multi-thread", "fs", "macros", "io-std", "io-util", "sync"] }
tokio-tungstenite = { version = "0.23.1", features = ["native-tls"] }
futures-util = "0.3.30"
clipboard = "0.5.0"
image = "0.25.2"
libc = "0.2.155"
sled = "0.34.7"
ksni = { version = "0.2.2", optional = true }
rodio = "0.19.0"
measure_time = "0.8.3"
memory-stats = "1.2.0"
backtrace = "0.3.73"
sha1 = "0.10.6"
base16ct = { version = "0.2.0", features = ["alloc"] }
jni = "0.21.1"
tokio-util = { version = "0.7.12", features = ["codec"] }
maplit = "1.0.2"
rusqlite = { version = "0.32.0", features = ["bundled"] }
bezier-rs = "0.4.0"

[features]
default=[]
tray=["ksni"]
x11=[]
production=[]

[target.'cfg(not(target_os = "android"))'.dependencies]
native-dialog = "0.7.0"

[target.'cfg(target_os = "android")'.dependencies]
skia-safe = {path = "third_party/rust-skia/skia-safe", package = "lento-skia-safe", version = "0.75.0", features = ["textlayout", "svg", "x11"], default-features = false}
android_logger = "0.11.0"
[target.'cfg(target_os = "linux")'.dependencies]
skia-safe = {path = "third_party/rust-skia/skia-safe", package = "lento-skia-safe", version = "0.75.0", features = ["textlayout", "svg", "x11"], default-features = false}
[target.'cfg(target_os = "macos")'.dependencies]
skia-safe = {path = "third_party/rust-skia/skia-safe", package = "lento-skia-safe", version = "0.75.0", features = ["textlayout", "svg"], default-features = false}

[dev-dependencies]
serial_test = "3.0"
static_assertions = "1.1"

raw-window-handle = { version = "0.5.0" }

[build-dependencies]
cfg_aliases = "0.2.1"

#[lib]
#name = "lento"
#path = "src/lib.rs"
#crate_type=["cdylib", "lib"]
#proc-macro = true
#
#[[bin]]
#path="src/lib.rs"
#name="lento_demo"

[[example]]
name = "hello"
crate_type=["cdylib", "lib"]