[package]
name = "lento"
readme = "README.md"
license = "MIT"

version = "0.1.0"
authors = ["KasonYang <me@kason.site>"]
edition = "2021"

[dependencies]
lento-core = { path = "packages/lento-core" }
lento-macros = { path = "packages/lento-macros" }

winit = { path = "third_party/winit" }
quick-js = { path = "third_party/quickjs-rs" }

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.11.0"

[features]
default = []
tray = ["lento-core/tray"]
x11 = ["lento-core/x11"]
production = ["lento-core/production"]
