[package]
name = "deft-ohos-logger"
version = "0.1.0"
edition = "2024"
description = "Deft logger for ohos"
license = "MIT"

[dependencies]
env_logger = "0.11.8"
log = "0.4.27"
ohos-hilog-binding = "0.1.0"
