[package]
name = "lento-macros"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Lento macros"

[lib]
proc-macro = true
path = "src/lib.rs"

[dependencies]
quote = "1.0.37"
syn = { version = "2.0.85",features = ["full"] }
#lento-core = { path = "../lento-core" }
